import glob from "glob";
import fs from "fs";

// These files are generated by antlr4ts, and contain code that is valid
// JavaScript (once the semantic predicates/actions are qualified with
// `this.`), but not valid TypeScript under our tsconfig. We also need to
// inject the import for the lexer's superclass.
glob.sync("./src/grammars/Yarn*.ts").forEach((fname: any) => {
  let src = fs.readFileSync(fname).toString();

  // Qualify bare semantic predicate / action calls with `this.`
  src = src.replace(/(?<!this\.)\bIsInWhenClause\(\)/g, "this.IsInWhenClause()");
  src = src.replace(/(?<!this\.)\bIsEndOfCommandKeyword\(\)/g, "this.IsEndOfCommandKeyword()");
  src = src.replace(/(?<!this\.)\bSetInWhenClause\(/g, "this.SetInWhenClause(");

  // Inject the superclass import for the lexer
  if (src.includes("extends IndentAwareLexer") && !src.includes("from \"../IndentAwareLexer\"")) {
    src = src.replace(
      'import { VocabularyImpl } from "antlr4ts/VocabularyImpl";',
      'import { VocabularyImpl } from "antlr4ts/VocabularyImpl";\nimport { IndentAwareLexer } from "../IndentAwareLexer";'
    );
  }

  src = `// @ts-nocheck\n${src}`;
  fs.writeFileSync(fname, src, { encoding: 'utf-8' });
});
